version: '3.8'

services:
  app:
    build: .
    image: "${IMAGE_NAME:-record-of-cashless-payment}:latest"
    ports:
      - "3001:3001"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - npm_config_registry=https://registry.npmjs.org/
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      - NO_PROXY=${NO_PROXY:-}
      - IMAP_SERVER=${IMAP_SERVER:-}
      - IMAP_USER=${IMAP_USER:-}
      - IMAP_PASSWORD=${IMAP_PASSWORD:-}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS:-}
    volumes:
      - ${FIREBASE_ADMIN_KEY_PATH:-/usr/src/app/firebase-admin-key.json}:/usr/src/app/firebase-admin-key.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500
    ipam:
      config:
        - subnet: 172.28.0.0/16
